### ISSUE TITLE
ERROR Plugin load failed: hexo-qiniu-sync

### ISSUE THREAD

**Issue by XinwenCheng** [gyk001/hexo-qiniu-sync#48]
```
npm uninstall hexo-qiniu-sync
```
删除七牛插件，并将_config.yml中plugin和七牛配置信息清除掉后，hexo d、hexo g和hexo s指令，还是会加载qiniu插件，因此总是会报错：ERROR Plugin load failed: hexo-qiniu-sync

hexo clean也执行过，还是报错。

请问如何解决？谢谢！

**Comment by XinwenCheng** [comment]
hexo clean也执行过，还是报错。

**Comment by XinwenCheng** [comment]
```
ERROR Plugin load failed: hexo-qiniu-sync
TypeError: Cannot read property 'secret_file' of undefined
    at Object.<anonymous> (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/hexo-qiniu-sync/config.js:8:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/hexo-qiniu-sync/index.js:9:14
    at /Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/username/Development/GitHub/GitHubUsername.github.io/node_modules/bluebird/js/release/promise.js:636:18)
```

**Comment by scorpioxiatian** [comment]
同求……

**Comment by NearEven** [comment]
1. 删除_config.yml中的hexo-qiniu-sync配置字段
2. 删除node_modules/文件夹下的qiniu文件夹和hexo-qiniu-sync 文件夹
It works !

**Comment by 2319048236** [comment]
为什么我重新安装这个插件后,还会出现ERROR Plugin load failed： hexo-qiniu-sync
