### ISSUE TITLE
不知道怎么得我不小心把hexo给弄崩溃了但是不知道为什恶魔找不到qnimg..

### ISSUE THREAD

**Issue by lozn00** [gyk001/hexo-qiniu-sync#52]
ypeError: Cannot read property 'secret_file' of undefined
    at Object.<anonymous> (F:\src\git_project\website2\node_modules\hexo-qiniu-sync\config.js:8:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (F:\src\git_project\website2\node_modules\hexo\lib\hexo\index.js:214:21)
    at F:\src\git_project\website2\node_modules\hexo-qiniu-sync\index.js:9:14
    at F:\src\git_project\website2\node_modules\hexo\lib\hexo\index.js:230:12
    at tryCatcher (F:\src\git_project\website2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:638:18)
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 10, Column 13]
  unknown block tag: qnimg
    at Object.exports.prettifyError (F:\src\git_project\website2\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (F:\src\git_project\website2\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (F:\src\git_project\website2\node_modules\nunjucks\src\environment.js:327:21)
    at F:\src\git_project\website2\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (F:\src\git_project\website2\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (F:\src\git_project\website2\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (F:\src\git_project\website2\node_modules\hexo\lib\hexo\post.js:253:16)
    at F:\src\git_project\website2\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (F:\src\git_project\website2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (F:\src\git_project\website2\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (F:\src\git_project\website2\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (F:\src\git_project\website2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
FATAL (unknown path) [Line 10, Column 13]
  unknown block tag: qnimg

**Comment by lozn00** [comment]
:\src\git_project\website2>hexo clean
ERROR Plugin load failed: hexo-qiniu-sync
TypeError: Cannot read property 'secret_file' of undefined
    at Object.<anonymous> (F:\src\git_project\website2\node_modules\hexo-qiniu-sync\config.js:8:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (F:\src\git_project\website2\node_modules\hexo\lib\hexo\index.js:214:21)
    at F:\src\git_project\website2\node_modules\hexo-qiniu-sync\index.js:9:14
    at F:\src\git_project\website2\node_modules\hexo\lib\hexo\index.js:230:12
    at tryCatcher (F:\src\git_project\website2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\src\git_project\website2\node_modules\bluebird\js\release\promise.js:638:18)
INFO  Deleted database.

**Comment by sumaolin** [comment]
没有配置七牛相关的密钥
